#!/usr/bin/env python3
""" Main """
import os
from time import sleep


# Create a child process
# using os.fork() method
# while True:
    # print("ok")
# exit(0)
pid = os.fork()

# pid greater than 0 represents
# the parent process
if pid > 0 :
    print("I am parent process:")
    print("Process ID:", os.getpid())
    print("Child's process ID:", pid)

# pid equal to 0 represents
# the created child process
else :
    while True:
        sleep(2)
        print("ok")
    print("\nI am child process:")
    print("Process ID:", os.getpid())
    print("Parent's process ID:", os.getppid())
